# Generated by Django 3.0.6 on 2020-05-29 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bookings', models.ManyToManyField(blank=True, to='api.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
                ('id_card', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='MessageState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('longitude', models.CharField(blank=True, max_length=2000)),
                ('latitude', models.CharField(blank=True, max_length=2000)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Booking')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000)),
                ('messageState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MessageState')),
                ('messageType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MessageType')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='api.Message'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
