# Generated by Django 3.0.6 on 2020-05-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='message',
            name='messageState',
        ),
        migrations.CreateModel(
            name='MessageEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Message')),
                ('messageState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MessageState')),
            ],
        ),
    ]
