# Generated by Django 3.0.6 on 2020-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='users',
            field=models.ManyToManyField(to='api.Employee'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookings',
            field=models.ManyToManyField(to='api.Booking'),
        ),
    ]
