# Generated by Django 3.0.6 on 2020-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200529_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='idName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
