# Generated by Django 3.0.6 on 2020-05-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='users',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='api.Booking'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Booking')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
            ],
        ),
    ]
