# Generated by Django 3.0.6 on 2020-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200525_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='latitude',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='transaction',
            name='longitude',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
