# Generated by Django 3.0.6 on 2020-05-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200525_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='longitude',
            field=models.CharField(max_length=2000),
        ),
    ]
