# Generated by Django 3.0.6 on 2020-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200525_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='longitude',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
